### ISSUE TITLE
Mapeamento de Grupos e Papéis

### ISSUE THREAD

**Issue by guisoaresdev** [grupoDecio/docs#13]
É importante que seja criado a documentação mapeando todos os grupos e papéis utilizados por cada processo do FLUIG do Grupo Décio

**Comment by agcoimbra** [comment]
Nos arquivos .process identificar 
managerMechanism="Pool Grupo"
managerMechanism="Pool Papel"

**Comment by guisoaresdev** [comment]
Issue finalizada
